# Generated by Django 5.1.1 on 2024-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEduu', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='No Summary', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Posts', max_length=50),
        ),
    ]
