# Generated by Django 4.2.16 on 2024-10-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myEduu', '0012_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
