# Generated by Django 4.2.16 on 2024-10-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myEduu', '0013_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='heading',
        ),
    ]
